apiVersion: v1
kind: Namespace
metadata:
  name: remotechrome
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  namespace: remotechrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      securityContext:
      containers:
      - name: chrome
        image: sec911/chrome:final
        ports:
        - containerPort: 6901
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: remotechrome
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 6901
  selector:
    app: chrome
  type: LoadBalancer